const responseObj = {
    today: new Date().toLocaleDateString(),
    hora: new Date().toLocaleTimeString(),
    fecha:new Date().toLocaleDateString(),
    Hora: new Date().toLocaleTimeString(),
    Fecha:new Date().toLocaleDateString(),
    HORA: new Date().toLocaleTimeString(),
    FECHA:new Date().toLocaleTimeString(),
    creador:"kevin fuentes",
    Creador:"kevin fuentes",
    CREADOR:"kevin fuentes",
    hola:"HOLA.. QUIERES SABER UN POCO DE MI?",
    HOLA:"HOLA.. QUIERES SABER UN POCO DE MI?",
    Hola:"HOLA.. QUIERES SABER UN POCO DE MI?",
    NOMBRE:"KEVIN",
    Nombre:"KEVIN",
    nombre:"KEVIN",
    HISTORIA:"Mi historia comenzó en 1943",
    Historia:"Mi historia comenzó en 1943",
    historia:"Mi historia comenzó en 1943",
    caracteristicas:"imitamos,automatizamos,no descansamos",
    CARACTERISTICAS:"imitamos,automatizamos,no descansamos",
    Caracteristicas:"imitamos,automatizamos,no descansamos",
    DESCRIPCION:"Aplicaciones médicas IA ofrece mejor resultados",
    Descripcion:"Aplicaciones médicas IA ofrece mejor resultados",
    descripcion:"Aplicaciones médicas IA ofrece mejor resultados",
    adios:"cuidate, gracias por visitar la pagina",
    ADIOS:"cuidate, gracias por visitar la pagina",
    Adios:"cuidate, gracias por visitar la pagina",
    como_estas:"bien y tu como estas?",
    futbol_o_basquetboll:"futbol y barcelona el mejor equipo",
    quien_gana_el_mundial:"de acuerdo a mis estadisticas ARGENTINA",
    Cuál_es_el_pasado_mañana_del_anteayer:"es miercoles",
    La_Inteligencia_Artificial_es_Humana:"no, nosotoros pensamos como humanos",
    Quién_es_Mark_Zuckerberg:"uno de los creadores y fundadores de Facebook", 
}
